### ISSUE TITLE
An exceptionCaught() event was fired

### ISSUE THREAD

**Issue by peterjurkovic** [ratpack/ratpack#1058] opened 2016-08-29 10:37 UTC
I've just been playing with a new version of `Ratpack 1.4.1`, but I am getting strange exception. I've tried downgrade to `1.3.3` with this version its working fine. Not sure whether it is Ratpack issue or netty. Originally this issue was created just on [stackoverflow.com](http://stackoverflow.com/questions/39196245/ratpack-an-exceptioncaught-event-was-fired)

    public class DownstreamUserService {
    
    	Logger log = LoggerFactory.getLogger(DownstreamUserService.class);
    
    	private HttpClient httpClient;
    	private ObjectMapper mapper;
    	private URI downstreamServerUri;
    
    	@Inject
    	public DownstreamUserService(HttpClient httpClient, Config config, ObjectMapper mapper) {
    		this.httpClient = httpClient;
    		this.mapper = mapper;
    		try {
    			downstreamServerUri = new URI("http://" + config.getHost() + ":" + config.getPort() + "/endpoint");
    		} catch (URISyntaxException e) {
    			log.error("",e);
    			throw new RuntimeException(e);
    		}
    	}
    
    	public Promise<User> load(){
    		return httpClient.get( downstreamServerUri )
    				.onError(e -> log.info("Error",e))
    				.map( res -> mapper.readValue(res.getBody().getBytes(), User.class));
    				
    	}
    }

Server

     public class App {
        
    	static Logger log = LoggerFactory.getLogger(App.class); 
    	
    	public static void main(String[] args) throws Exception {
    		RatpackServer.start(s -> s 
    		 // bindings..
    		 .handlers( chain -> chain
    
    			 .get("user", c -> {
    				 DownstreamUserService service = c.get(DownstreamUserService.class);
    				 service.load().then( user -> c.render( json(user) ));
    			 })
    	}
    }

Stacktrace:

        [2016-08-28 22:58:24,979] WARN  [ratpack-compute-1-2] i.n.c.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
    io.netty.handler.codec.PrematureChannelClosureException: channel gone inactive with 1 missing response(s)
    	at io.netty.handler.codec.http.HttpClientCodec$Decoder.channelInactive(HttpClientCodec.java:261)
    	at io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:220)
    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:255)
    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:241)
    	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:234)
    	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1329)
    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:255)
    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:241)
    	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:908)
    	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:744)
    	at io.netty.util.concurrent.SingleThreadEventExecutor.safeExecute(SingleThreadEventExecutor.java:451)
    	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
    	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:306)
    	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
    	at ratpack.exec.internal.DefaultExecController$ExecControllerBindingThreadFactory.lambda$newThread$0(DefaultExecController.java:136)
    	at ratpack.exec.internal.DefaultExecController$ExecControllerBindingThreadFactory$$Lambda$129/1240843015.run(Unknown Source)
    	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
    	at java.lang.Thread.run(Thread.java:745)

**Comment by danhyun** [comment] 2016-08-29 14:06
Hello,

I've tried to reproduce without success, please refer to https://github.com/danhyun/ratpack-client-example

**Comment by peterjurkovic** [comment] 2016-08-29 14:08
Here is a link to a project where you can reproduce it: https://github.com/peterjurkovic/ratpack-demo

**Comment by danhyun** [comment] 2016-08-29 16:43
After a little digging it appears as if Wiremock is not properly closing the response.

It looks like it closes the connection before terminating the request somehow, I'll do a bit more digging later.

**Comment by danhyun** [comment] 2016-08-29 18:45
So here's something interesting.

If you supply `Content-length` in the wiremock stub, the netty http client codec does not complain about missing any frames.

```
        wireMockServer.stubFor(get(urlEqualTo("/endpoint"))
        		.willReturn(
        				aResponse()
					.withHeader("Content-length", "41")
	    				.withHeader("Content-Type", "application/json")
	    				.withBody( USER_JSON )
	    				.withFixedDelay(100)
    		));
```

I've changed the `USER_JSON` here to be `{"name":"gordon_freeman","email":"email"}`.

My feeling says that Wiremock is not properly signalling end of transfer chunks.
It looks like Wiremock finishes response bodies by forcibly ending the connection.

**Comment by peterjurkovic** [comment] 2016-08-29 18:49
Well spotted, but why does Ratpack 1.3.3 handles this issue but 1.4.1 not?

**Comment by danhyun** [comment] 2016-08-29 18:50
We've upgrade Netty as a part of the 1.4 release, I also believe this is related to #1056

**Comment by danhyun** [comment] 2016-08-29 19:21
Something in here changed the behavior ;) https://github.com/netty/netty/compare/netty-4.1.0.CR7...netty-4.1.4.Final

**Comment by alkemist** [comment] 2016-08-29 23:38
@peterjurkovic it's because of the `true` here: https://github.com/ratpack/ratpack/blob/37c4938bb7d18a7b0334b2c7686bcf73ead10ff5/ratpack-core/src/main/java/ratpack/http/client/internal/RequestActionSupport.java#L180-L180

This tells Netty to consider it an exceptional condition if the server closes the connection before emitting a response after we send it a request. 

My read of this is that the server you are talking to is behaving questionably, and the behaviour from Netty is questionable here. Responses should always include either a `Transfer-Encoding` or `Content-Length` header.

In the very least, we need to fail better here. At best, we could just consider connection closure to be terminal and send back the bytes we got. This isn't entirely safe though, so I'll need to think about it. For example, there's no way of knowing in this case whether the server got to send everything it wanted or whether something severed the connection.

**Comment by danhyun** [comment] 2016-08-30 14:41
Bringing some more light to the table:

This is a simple netty http client, when I issue a request against @peterjurkovic 's Wiremock stub, Netty 4.1.4Final and Netty 4.1.5.Final fail to see the last chunked content before Wiremock abruptly cuts closes the connection.

```
import io.netty.bootstrap.Bootstrap;
import io.netty.channel.*;
import io.netty.channel.nio.NioEventLoopGroup;
import io.netty.channel.socket.SocketChannel;
import io.netty.channel.socket.nio.NioSocketChannel;
import io.netty.handler.codec.http.*;
import io.netty.util.CharsetUtil;

import java.net.URI;

public class Main {
    public static void main(String[] args) throws InterruptedException {
        EventLoopGroup elg = new NioEventLoopGroup();
        try {
            Bootstrap b = new Bootstrap();
            b.group(elg)
                    .channel(NioSocketChannel.class)
                    .handler(new ClientInitializer());

            URI uri = URI.create("http://localhost:9999/endpoint");

            Channel ch = b.connect(uri.getHost(), uri.getPort()).sync().channel();

            HttpRequest request = new DefaultFullHttpRequest(
                HttpVersion.HTTP_1_1, HttpMethod.GET, uri.getRawPath()
            );

            request.headers().set(HttpHeaderNames.HOST, uri.getHost());
            request.headers().set(HttpHeaderNames.CONNECTION, HttpHeaderValues.CLOSE);
            request.headers().set(HttpHeaderNames.ACCEPT_ENCODING, HttpHeaderValues.GZIP);

            ch.writeAndFlush(request);

            ch.closeFuture().sync();

        } finally {
            elg.shutdownGracefully();
        }
    }
}

class ClientInitializer extends ChannelInitializer<SocketChannel> {
    @Override
    protected void initChannel(SocketChannel ch) throws Exception {
        ChannelPipeline p = ch.pipeline();
        p.addLast(new HttpClientCodec());
        p.addLast(new HttpContentDecompressor());
        p.addLast(new ClientHandler());
    }
}

class ClientHandler extends SimpleChannelInboundHandler<HttpObject> {
    @Override
    protected void channelRead0(ChannelHandlerContext ctx, HttpObject msg) throws Exception {
        if (msg instanceof HttpResponse) {
            HttpResponse response = (HttpResponse) msg;

            if (!response.headers().isEmpty()) {
                response.headers().names()
                        .forEach(name ->
                                response.headers().getAll(name)
                                        .forEach(value -> System.out.println("HEADER: " + name + " = " + value)));
            }

            if (HttpUtil.isTransferEncodingChunked(response)) {
                System.out.println("CHUNKED CONTENT {");
            } else {
                System.out.println("CONTENT {");
            }
        }

        if (msg instanceof HttpContent) {
            HttpContent content = (HttpContent) msg;

            System.out.println(content.content().toString(CharsetUtil.UTF_8));
            System.out.flush();

            if (content instanceof LastHttpContent) {
                System.out.println("} END OF CONTENT");
                ctx.close();
            }
        }
    }

    @Override
    public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) throws Exception {
        cause.printStackTrace();
        ctx.close();
    }
}
```

This code was lifted from http://netty.io/4.1/xref/io/netty/example/http/snoop/package-summary.html

This verifies Luke's assessment that both Netty client codec and Wiremock are behaving questionably.

**Comment by danhyun** [comment] 2016-08-30 15:04
Additional digging reveals that this change in behavior was introduced in 4.1.2.Final

Here are the changes between 4.1.1.Final and 4.1.2.Final https://github.com/netty/netty/compare/netty-4.1.1.Final...netty-4.1.2.Final

**Comment by danhyun** [comment] 2016-08-30 16:10
For some reason in 4.1.1.Final if you specify `Accept-Encoding: gzip` it doesn't interpret the response as chunked but in 4.1.2.Final onward it does interpret it as chunked which is why the last content is never seen.

The two versions seem to be parsing header values differently.
4.1.1.Final does not see any `transfer-encoding: chunked` whereas 4.1.2.Final and beyond do.

**Comment by danhyun** [comment] 2016-08-30 16:21
This is the line that changed the behavior in decoding http content:

https://github.com/netty/netty/pull/5429/files

So wiremock needs to either set `content-length` or `transfer-encoding: chunked` and we need to figure out a way for Netty's http decoder to handle these abrupt forced closed connections.

In general if the remote server uses keep-alive we'll have additional problems here as we'll never know when the server has actually finished sending a response. In wiremock's case it closes the connection but it seems that netty will just hang indefinitely or until the socket gets closed after some timeout.

**Comment by alkemist** [comment] 2016-08-31 01:09
Nice sleuthing @danhyun

**Comment by alkemist** [comment] 2016-09-07 22:39
I don't think we can “fix” this. What we can do though is fail better by propagating the PrematureChannelCloseException out via the promise.

**Comment by danhyun** [comment] 2016-09-07 22:48
Agreed, at any rate we shouldn't swallow exceptions when it's definitely bad behavior on remote side. User should handle this IMO

**Closed** 2016-09-12 04:10 UTC
