### ISSUE TITLE
Direct Memory Leak

### ISSUE THREAD

**Issue by tylerbenson** [ratpack/ratpack#1081] opened 2016-10-14 20:33 UTC
I've discovered a direct memory leak via the `io.netty.leakDetectionLevel` system property.  Here's an isolated test case you can run that will result in a `ERROR io.netty.util.ResourceLeakDetector - LEAK: ByteBuf.release() was not called before it's garbage-collected.` error.

```groovy
import ratpack.http.client.ReceivedResponse
import ratpack.server.RatpackServer
import ratpack.test.ApplicationUnderTest
import ratpack.test.MainClassApplicationUnderTest
import ratpack.test.http.TestHttpClient
import spock.lang.AutoCleanup
import spock.lang.Shared
import spock.lang.Specification
import spock.lang.Unroll

import java.nio.charset.Charset

class LeakTest extends Specification {

    static {
        System.setProperty("io.netty.leakDetectionLevel", "paranoid")
    }

    public static void main(String... args) {
        RatpackServer.start {
            it.handlers {
                it.all {
                    it.response.status(200).send()
                    // it.render("") // <- also shows the leak.
                }
            }
        }
    }

    @AutoCleanup
    @Shared
    ApplicationUnderTest aut = new MainClassApplicationUnderTest(LeakTest.class)

    @Delegate
    TestHttpClient client = TestHttpClient.testHttpClient(aut)

    @Unroll
    def "leak"() {
        setup:
        def ReceivedResponse response = client.get(url.toString())
        def responseText = response.getBody().getText(Charset.defaultCharset())

        expect:
        responseText == ""
        response.statusCode == 200

        where:
        url << (1..20)
    }
}
```

(This might be an issue with just the test harness)
I've reproduced this in Ratpack 1.3.0 and 1.4.2.

**Comment by alkemist** [comment] 2016-10-21 09:30
I'm confident that this is a duplicate of #1072.

This has been fixed for the pending 1.4.3 release.

**Closed by alkemist** 2016-10-21 09:30 UTC
