### ISSUE TITLE
Error in ScriptEngine.java line 90 when running a groovy script in project using latest ratpack runtime 

### ISSUE THREAD

**Issue by woodmawa** [ratpack/ratpack#1638] opened 2022-03-01 16:47 UTC
i'm trying try and use ratpack in a groovy 4 project using ratpack as runtime implementation in my gradle file  

i create a simple script like this 

```
@Grab("io.ratpack:ratpack-groovy:10.0-milestone-3")


import static ratpack.groovy.Groovy.ratpack

ratpack {
    handlers {
        get {
            render "Hello, World!"
        }
    }
}

```

when i run this script in the intellij IDE i get this error

```
Caught: java.lang.NoSuchFieldError: verifier
java.lang.NoSuchFieldError: verifier
	at ratpack.groovy.script.internal.ScriptEngine$2$1.<init>(ScriptEngine.java:90)
	at ratpack.groovy.script.internal.ScriptEngine$2.createCompilationUnit(ScriptEngine.java:88)
	at ratpack.groovy.script.internal.ScriptEngine.compile(ScriptEngine.java:62)
	at ratpack.groovy.script.internal.ScriptEngine.create(ScriptEngine.java:51)
	at ratpack.groovy.internal.capture.RatpackDslScriptCapture.lambda$apply$0(RatpackDslScriptCapture.java:44)
	at ratpack.groovy.internal.capture.RatpackScriptBacking.withBacking(RatpackScriptBacking.java:37)
	at ratpack.groovy.internal.capture.RatpackDslClosures.capture(RatpackDslClosures.java:97)
	at ratpack.groovy.internal.capture.RatpackDslScriptCapture.apply(RatpackDslScriptCapture.java:43)
	at ratpack.groovy.Groovy$Script.doApp(Groovy.java:340)
	at ratpack.groovy.Groovy$Script.lambda$app$0(Groovy.java:257)
	at ratpack.server.internal.RatpackServerDefinition.build(RatpackServerDefinition.java:43)
	at ratpack.server.internal.DefaultRatpackServer.lambda$buildUserDefinition$4(DefaultRatpackServer.java:216)
	at ratpack.impose.Impositions.impose(Impositions.java:117)
	at ratpack.server.internal.DefaultRatpackServer.buildUserDefinition(DefaultRatpackServer.java:214)
	at ratpack.server.internal.DefaultRatpackServer.start(DefaultRatpackServer.java:117)
	at ratpack.server.RatpackServer.start(RatpackServer.java:93)
	at ratpack.groovy.internal.StandaloneScriptBacking.execute(StandaloneScriptBacking.java:53)
	at ratpack.groovy.internal.StandaloneScriptBacking.execute(StandaloneScriptBacking.java:29)
	at ratpack.groovy.internal.capture.RatpackScriptBacking.execute(RatpackScriptBacking.java:44)
	at ratpack.groovy.Groovy.ratpack(Groovy.java:111)
	at simpleServer.run(simpleServer.groovy:7)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

```

when  i look at the deconstructed code file it shows this 

```
    return new GroovyClassLoader(parentLoader, compilerConfiguration) {
      @Override
      protected CompilationUnit createCompilationUnit(CompilerConfiguration config, CodeSource source) {
        return new CompilationUnit(config, source, this) {
          {
            verifier = new Verifier() {  //line 90 is here 
              @Override
              public void visitClass(ClassNode node) {
                if (node.implementsInterface(ClassHelper.GENERATED_CLOSURE_Type)) {
                  AnnotationNode lineNumberAnnotation = new AnnotationNode(LINE_NUMBER_CLASS_NODE);
                  lineNumberAnnotation.addMember("value", new ConstantExpression(node.getLineNumber(), true));
                  node.addAnnotation(lineNumberAnnotation);
                }

                super.visitClass(node);
              }
            };
          }
        };
      }
    };

```
verifier is used - but not declared 

I was hoping to use latest groovy but use the ratpack latest as runtimeOnly dependency but cant get this to run 

my build.gradle is as follows 

```
plugins {
    id 'groovy'
    id 'java'
    id "io.ratpack.ratpack-groovy" version "1.10.0-milestone-3"
}

group 'org.example'
version '1.0-SNAPSHOT'

String groovyVersion = "4.0.0"

repositories {
    maven {
        url "https://plugins.gradle.org/m2/"
    }
    maven {
        url "https://mvnrepository.com/artifact/org.apache.groovy/groovy"}

    mavenCentral()
}

//ratpack is a runtime dependency - its handled here by the plugin
dependencies {
    implementation group: "org.apache.groovy", name: 'groovy', version: "${groovyVersion}"
    implementation group: 'org.apache.ivy', name: 'ivy', version: '2.5.0'

    //implementation group: 'org.apache.groovy', name: 'groovy-json', version: "${groovyVersion}"

    runtimeOnly group: 'org.slf4j', name: 'slf4j-api', version: '2.0.0-alpha6'
    runtimeOnly group: 'ch.qos.logback', name: 'logback-classic', version: '1.3.0-alpha14'


    //testing
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.2'

//    testImplementation group: 'org.apache.groovy', name: 'groovy-test', version: "${groovyVersion}"
    testImplementation group: 'org.spockframework', name: 'spock-core', version: '2.2-M1-groovy-4.0'
//    testImplementation group: 'org.spockframework', name: 'spock-core', version: '2.2-M1-groovy-2.5'


    testRuntimeOnly group: 'io.ratpack', name: 'ratpack-groovy-test', version: '1.10.0-milestone-4'


}

test {
    useJUnitPlatform()
}
```

**Comment by johnrengelman** [comment] 2022-03-01 16:50
Duplicate of https://github.com/ratpack/ratpack/issues/1616
Ratpack does not support Groovy 3+ yet. This will be included in the 20 release.

**Closed by johnrengelman** 2022-03-01 16:50 UTC

**Comment by woodmawa** [comment] 2022-03-01 16:57
hi john - ok i can accept that - however the code error is still an error surely ?

line 90 has `verifier = new Verifier()`  but verifier is not declared - which is what the error shows.  

i'm using ratpack as a runtimeOnly dependency - so the code is the code in the runtime built as per build today

**Comment by johnrengelman** [comment] 2022-03-01 17:01
It's because the `Verifier` class was dropped in Groovy 3.0 and Ratpack's integration no longer functions on that version.
In order to support it, we'll have to have a breaking change in our implementations, thus why it needs to wait for Ratpack 2.0.

**Comment by woodmawa** [comment] 2022-03-01 17:14
ah ok - i'll getting serious with ratpack immediately as i dont want to go that far back in groovy versions 

with groovy version 4 now launched are you going to skip org.codehaus groovy 3 - or jump to org.apache groovy 4 direct?

**Comment by woodmawa** [comment] 2022-03-01 17:19
ok - thanks for the update i'll try and keep an eye out and put the current build into play mode when i get some quite space whilst i wait 

i've been looking at the vertx library at present so i'll keep that going for now
