### ISSUE TITLE
ParallelBatch and onError

### ISSUE THREAD

**Issue by jdbevan** [ratpack/ratpack#1235] opened 2017-06-27 10:38 UTC
I wrote some crappy code that looked like this:

```
List<Promise> promises = someList.stream()
    .map(item -> {
        return service.doAsyncThing(item)
            .onError(TheWorstExceptionPossible.class, { e ->
                log.error("Ahh, everything broke!", e);
            });
    })
    .collect(Collectors.toList());

return ParallelBatch.of(promises).yieldAll().map(results -> {
    return results.stream.anyMatch(execResult -> execResult.getError() || !execResult.getValue());
});
```

The ParallelBatch API lead me to believe that `yieldAll` would return a `Promise<List<ExecResult<T>>>`.

If, like me, you write stupid things like `.onError` handlers on your promises before passing them into ParallelBatch, you actually get the original Promise back in the `List<ExecResult<T>>`, not an ExecResult...

The culprit is [this line](https://github.com/ratpack/ratpack/blob/d8f97b8a21fa7ea8bb533ed41d6fe3aeaff041f0/ratpack-exec/src/main/java/ratpack/exec/util/internal/DefaultParallelBatch.java#L57) in DefaultParallelBatch:
```
List<ExecResult<T>> results = Types.cast(promises);
```

Whilst I have been suitably chastised by in-production error logs from this heinous mistake, perhaps the DefaultParallelBatch could be modified to **actually** always return a List of ExecResult and not some blindly type-cast Promise?

For your humble consideration, maybe the following code would be a better solution than the current `@SuppressWarnings("unchecked") T cast = (T) o;`

```
List<ExecResult<T>> results = promises.stream().map(p -> {
    return ExecResult.of(Result.<T>error(new YouShouldNeverCallOnErrorException("because then ParallelBatch can't obtain the ExecResult")));
}).collect(Collectors.toList());
```

**Comment by ldaley** [comment] 2017-11-05 23:43
@jdbevan thanks for the report. 

It's not clear to me what the actual symptom is here. AFAICT, this is all working as intended. If you catch the error, the net value for the promise is just going to be `null`, which is as expected.

Are you expecting to have the exec result convey the error? If so, you need to rethrow the exception in your error handler to have it keep propagating.

I'm going to speculatively close this as wontfix because I don't think there's a problem, but I'll happily reopen if you provide more info.

**Closed** 2017-11-05 23:46 UTC

**Comment by jdbevan** [comment] 2017-11-06 08:56
Apologies @ldaley I could have been clearer.

The problem was that we got **the original Promise back** in the `List<ExecResult<T>>`, instead of a `null` value or an `ExecResult` containing a failure. However, I can't seem to reproduce the behaviour... I should have put together a better example at the time.
